Proposal03
jralls/gtk-mac-bundler pull request #16
Opened 2022-12-27 10:26 UTC by Blady-Com

Add few changes that make it easier for the test and complete the proposed example.

2022-12-27 16:33 UTC, jralls requested changes
I heartily agree with getting rid of giggle in favor of gtk3-demo, though considering that Gtk4 is the currently developed version gtk4-demo would be more appropriate still.

I don't understand the motivation for implementing `__main__` in main.py.

2022-12-27 16:33 UTC, jralls commented on bundler/main.py
> -import sys, os
`os` is needed for `os.path.exists()` on line ``.

2022-12-27 16:33 UTC, jralls commented on examples/Info-gtk3-demo.plist
> +    <string>(C) 1997-2013 The GTK+ Team</string>
Shouldn't that be 2023?

2022-12-27 16:33 UTC, jralls commented on examples/Info-gtk3-demo.plist
> +    <string>3.24.33</string>
The full version should be `Gtk3-Demo 3.24.33`. But the current release of gtk3 is 3.24.36 and while it's definitely in maintenance mode there are sure to be many more releases so whatever you put here will be obsolete pretty soon. Maybe better to say `<string>Gtk3-Demo 3.24.XX</string><!-- In a real project you'll edit this on every release. -->`.

2022-12-27 16:33 UTC, jralls commented on examples/gtk3-demo.bundle
> +  </gir>
Huh? Gtk3-demo is pure C, no bindings required.

2022-12-27 16:33 UTC, jralls commented on examples/gtk3-demo.bundle
> +
This is even less appropriate than including gir.

2022-12-27 20:33 UTC, Blady-Com commented on bundler/main.py
> -import sys, os
Yes indeed I was confused because this import was hidden by further `import *`.

2022-12-27 20:33 UTC, Blady-Com commented on examples/Info-gtk3-demo.plist
> +    <string>(C) 1997-2013 The GTK+ Team</string>
I imagine so, I've just copied and pasted the about box of gtk3-demo-application.

2022-12-27 20:38 UTC, Blady-Com commented on examples/Info-gtk3-demo.plist
> +    <string>3.24.33</string>
According to Apple documentation CFBundleVersion is mostly numeric.
Concerning its value and that of the previous copyright year, my intend is to propose just an example of Info.plist. It is not intend to follow GTK release.

2022-12-27 20:42 UTC, Blady-Com commented on examples/gtk3-demo.bundle
> +  </gir>
Yes, indeed my intent was to give an example of most of the possibilities. To be more realistic I'll put in comment.

2022-12-27 20:44 UTC, Blady-Com commented on examples/gtk3-demo.bundle
> +
Yes, here this time in comment to show macro possibilities.

2022-12-27 20:46 UTC, Blady-Com commented
> I don't understand the motivation for implementing `__main__` in main.py.

Well, I look for running the `main` function in `main.py` from the command line.
How to do that otherwise?

2022-12-30 02:08 UTC, jralls commented
When you `make install` it creates a `gtk-mac-bundler` in ~/.local/bin. You run that. `bundler` is a python module, it's supposed to be `import`ed into a python program, not to run on its own.

2022-12-30 02:11 UTC, jralls commented on bundler/main.py
> +        print("Usage: main.py <bundle description file>")
Nope. Fix the typo but leave the usage so that the output is correct when run from `gtk-mac-integration` as it should be.

2022-12-31 11:43 UTC, Blady-Com commented on bundler/main.py
> +        print("Usage: main.py <bundle description file>")
Did you mean gtk-mac-bundler?
I missed that `sys.argv` is used as print value and not `argv` parameter of `main`.
As long as passing arguments as much as passing all including the first one in gtk_mac-bundler:
`bundler.main.main(sys.argv)`
and then:
`print("Usage: %s <bundle description file>" % (argv[0]))`
Or even nothing:
`bundler.main.main()`
and then:
`print("Usage: %s <bundle description file>" % (sys.argv[0]))`
The latter has my preference, if ok I'll post a change.
(Of course the all main will be refactored accordingly)

2022-12-31 17:13 UTC, jralls commented on bundler/main.py
> -import sys, os
What `import *`? That's not even valid python.

2022-12-31 17:15 UTC, jralls commented on examples/gtk3-demo.bundle
> +
Pick something that doesn't involve Gtk2 and include an explanatory comment.

2022-12-31 17:19 UTC, jralls commented on examples/gtk3-demo.bundle
> +  </gir>
In that case it also needs an explanatory comment to go with it.

2022-12-31 17:30 UTC, jralls commented on bundler/main.py
> +        print("Usage: main.py <bundle description file>")
> Did you mean gtk-mac-bundler?

Yes.

I think that `bundler.main.main(sys.argv)` better expresses the intent than does `…main()` and using `sys.argv` directly in `main()`. I agree that mixing it is awkward.

2022-12-31 18:22 UTC, jralls commented on examples/gtk3-demo.bundle
> +
On second thought,  a separate bundle-template.xml that has examples of all of the possible elements and attributes with explanatory comments would be better than loading up gtk3-demo.bundle with a bunch of extraneous elements.

 [Proper documentation](https://gitlab.gnome.org/GNOME/gtk-mac-bundler/-/issues/15#note_1629890) would be even better.

2022-12-31 19:29 UTC, closed without merging